/** Writes docs/naming.md from src/core/vocabulary.ts. `npm run naming`. */
import { writeFileSync } from 'node:fs';
import { VOCABULARY } from '../src/core/vocabulary.js';
import { registry } from '../src/index.js';

const usedBy = new Map<string, Set<string>>();
for (const def of registry.list()) {
  for (const key of Object.keys(def.keys)) {
    if (!usedBy.has(key)) usedBy.set(key, new Set());
    usedBy.get(key)!.add(def.vendor);
  }
}

const rows = Object.entries(VOCABULARY)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([key, unit]) => `| \`${key}\` | ${unit ?? '— (state/event)'} | ${[...(usedBy.get(key) ?? [])].sort().join(', ')} |`);

const content = `# Telemetry naming

<!-- Generated by \`npm run naming\`. Do not edit by hand; edit src/core/vocabulary.ts. -->

Every decoder emits the same keys with the same units.

## Rules

1. Keys are \`snake_case\` ASCII: \`^[a-z][a-z0-9]*(_[a-z0-9]+)*$\`.
2. Bare name = the device's built-in sensor. Extra sensors of the same
   quantity get a suffix: \`_external\`, \`_1\` \`_2\` \`_3\`, \`_x\` \`_y\` \`_z\`,
   \`_in\` \`_out\`, \`_eq\` \`_max\`. Single-phase: \`current\`; three-phase:
   \`current_1..3\`.
3. One key, one unit. Different unit = different key (\`tvoc\` µg/m³ vs
   \`tvoc_index\`; \`pressure\` kPa vs \`barometric_pressure\` hPa). Unscaled
   counts go on \`<key>_raw\`, never on \`<key>\`.
4. Every key is in the table below. Registration and tests reject anything
   else.
5. States and events are strings. Booleans only for two-valued flags
   (\`battery_low\`). Wire codes are not exposed.

Device metadata (firmware, serial, multipliers, header bytes) is not
telemetry; it is in \`attributes\` with \`detailed: true\`.

## Vocabulary

| Key | Unit | Emitted by |
|---|---|---|
${rows.join('\n')}
`;

writeFileSync(new URL('../docs/naming.md', import.meta.url), content);
process.stdout.write(`wrote docs/naming.md — ${rows.length} keys\n`);
