/**
 * Regenerates docs/naming.md from src/core/vocabulary.ts. Run with
 * `npm run naming`. CI fails if the committed file is stale.
 */
import { writeFileSync } from 'node:fs';
import { VOCABULARY } from '../src/core/vocabulary.js';
import { registry } from '../src/index.js';

const usedBy = new Map<string, Set<string>>();
for (const def of registry.list()) {
  for (const key of Object.keys(def.keys)) {
    if (!usedBy.has(key)) usedBy.set(key, new Set());
    usedBy.get(key)!.add(def.vendor);
  }
}

const rows = Object.entries(VOCABULARY)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([key, unit]) => `| \`${key}\` | ${unit ?? '— (state/event)'} | ${[...(usedBy.get(key) ?? [])].sort().join(', ')} |`);

const content = `# Telemetry naming

<!-- Generated by \`npm run naming\`. Do not edit by hand; edit src/core/vocabulary.ts. -->

Every decoder in this library emits the same vocabulary. A \`temperature\` is
degrees Celsius whether it came from a Milesight, a Dragino or an Ellenex
sensor; a \`distance\` is millimetres. The point is that an alarm rule written
once works across the fleet.

## Rules

1. **Keys are \`snake_case\`, lowercase ASCII.** \`^[a-z][a-z0-9]*(_[a-z0-9]+)*$\`.
2. **The bare name is the device's primary or built-in sensor** for that
   quantity. Additional sensors of the same quantity take a suffix:
   \`_external\`, \`_1\` \`_2\` \`_3\`, \`_x\` \`_y\` \`_z\`, \`_in\` \`_out\`, \`_eq\` \`_max\`.
   A Dragino LHT65 reports \`temperature\` (its own sensor) and
   \`temperature_external\` (the probe). A single-phase Netvox meter reports
   \`current\`; a three-phase one reports \`current_1\`, \`current_2\`, \`current_3\`.
3. **One key, one unit, forever.** The same quantity in a different unit is a
   different key: \`tvoc\` is µg/m³, \`tvoc_index\` is dimensionless;
   \`pressure\` is kPa, \`barometric_pressure\` is hPa. A reading whose scale is
   only known out of band is never put on the engineering key: Ellenex
   sensors without a scaling profile report \`level_raw\`, not \`level\`.
4. **Every key is in the vocabulary table below.** A decoder that declares a
   key outside it, or with a different unit, fails to register. The test
   suite also checks every emitted reading against the table.
5. **States and events are strings** (\`position: "tilt"\`,
   \`leakage_status: "leak"\`). Booleans only for genuinely two-valued flags
   (\`battery_low\`). The raw wire code behind a label is not exposed.

Device metadata — firmware version, serial number, multipliers, undocumented
header bytes — is not telemetry. It is returned under \`attributes\` when you
ask for \`detailed: true\` and is otherwise absent.

## Vocabulary

| Key | Unit | Emitted by |
|---|---|---|
${rows.join('\n')}
`;

writeFileSync(new URL('../docs/naming.md', import.meta.url), content);
process.stdout.write(`wrote docs/naming.md — ${rows.length} keys\n`);
