/**
 * Regenerates docs/supported-devices.md from the registry, so the table can
 * never drift from the code. Run with `npm run devices`.
 */
import { writeFileSync } from 'node:fs';
import { registry } from '../src/index.js';

const rows: string[] = [];
let totalVariants = 0;

for (const vendor of registry.vendors()) {
  const models = registry.list().filter((d) => d.vendor === vendor);
  rows.push(`\n### ${vendor}\n`);
  rows.push('| Decoder | Covers | fPort | Description |');
  rows.push('|---|---|---|---|');
  for (const def of models) {
    const variants = def.aliases?.length ?? 0;
    totalVariants += 1 + variants;
    const covers = variants > 0 ? `${1 + variants} model names` : '1 model';
    rows.push(`| \`${def.model}\` | ${covers} | ${def.fPort ?? '—'} | ${def.description} |`);
  }
  const sources = [...new Set(models.map((m) => m.source))];
  for (const source of sources) rows.push(`\n_Source: ${source}_`);
}

const decoders = registry.list().length;

const content = `# Supported devices

<!-- Generated by \`npm run devices\`. Do not edit by hand. -->

**${decoders} decoders covering ${totalVariants} model names across ${registry.vendors().length} vendors.**

Model names are matched case-insensitively and ignore separators, so \`EM400-TLD\`,
\`em400tld\` and \`EM400 TLD\` all resolve to the same decoder. That is not a
nicety: in a real fleet the same device arrives spelled three different ways
from three different integrations.
${rows.join('\n')}

## Why the counts differ

A Netvox R718N1 and an R718N1100 are the same device with a different current
transformer — 30 A versus 1000 A. The wire format is identical; the reading is
always milliamps and the range is handled by the device plus the multiplier
byte. Writing 12 near-identical decoders for that family would be 12 places for
a bug to hide. One decoder, generated aliases.
`;

writeFileSync(new URL('../docs/supported-devices.md', import.meta.url), content);
process.stdout.write(`wrote docs/supported-devices.md — ${decoders} decoders, ${totalVariants} model names\n`);
