/** Writes docs/supported-devices.md from the registry. `npm run devices`. */
import { writeFileSync } from 'node:fs';
import { accessorName } from '../src/core/registry.js';
import { registry } from '../src/index.js';

const rows: string[] = [];
let totalVariants = 0;

for (const vendor of registry.vendors()) {
  const models = registry.list().filter((d) => d.vendor === vendor);
  const ns = vendor.toLowerCase();
  rows.push(`\n## ${vendor}\n`);
  rows.push(`\`\`\`ts\nimport { ${ns} } from 'lorawan-decoders/${ns}';\n\`\`\`\n`);
  rows.push('| Model | Name to pass | Accessor | Also answers to | fPort | Description |');
  rows.push('|---|---|---|---|---|---|');
  for (const def of models) {
    const aliases = [...(def.aliases ?? [])];
    totalVariants += 1 + aliases.length;
    const also = aliases.length === 0 ? '—'
      : aliases.length <= 4 ? aliases.map((a) => `\`${a}\``).join(', ')
        : `${aliases.slice(0, 3).map((a) => `\`${a}\``).join(', ')} … (${aliases.length} names)`;
    rows.push(
      `| ${def.model} | \`'${def.model.toLowerCase()}'\` | \`${ns}.${accessorName(def.model)}\` | ${also} | ${def.fPort ?? '—'} | ${def.description} |`,
    );
  }
  rows.push('\n### Telemetry keys\n');
  rows.push('| Model | Keys (unit) |');
  rows.push('|---|---|');
  for (const def of models) {
    const keys = Object.entries(def.keys)
      .map(([k, u]) => (u === null ? `\`${k}\`` : `\`${k}\` (${u})`))
      .join(', ');
    rows.push(`| ${def.model} | ${keys} |`);
  }
  const sources = [...new Set(models.map((m) => m.source))];
  for (const source of sources) rows.push(`\n_Source: ${source}_`);
}

const decoders = registry.list().length;

const content = `# Supported devices

<!-- Generated by \`npm run devices\`. Do not edit by hand. -->

**${decoders} decoders covering ${totalVariants} model names across ${registry.vendors().length} vendors.**

- Accessor: \`milesight.em310_tilt(payload)\`. Model name lowercased, separators → \`_\`. Aliases too.
- Name string: \`decode('milesight', 'em310-tilt', payload)\`. Case and separators ignored.
  \`isModel(vendor, name)\` validates; unknown names throw with a suggestion.

Keys are from [naming.md](naming.md). No unit = state or event (string).
${rows.join('\n')}

## Decoders vs model names

Netvox CT-rating suffixes (R718N1, R718N17, R718N1100…) share one wire format,
so one decoder serves the family and the names are aliases.
`;

writeFileSync(new URL('../docs/supported-devices.md', import.meta.url), content);
process.stdout.write(`wrote docs/supported-devices.md — ${decoders} decoders, ${totalVariants} model names\n`);
